version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: golpe-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Golpe
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - rede
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -proot"]
      interval: 10s
      retries: 5

  app:
    image: verificadoracr.azurecr.io/verificador:latest
    restart: always
    container_name: golpe-backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_URL: "jdbc:mysql://mysql:3306/Golpe?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "80:8080"
    networks:
      - rede

networks:
  rede:

volumes:
  mysql-data:
    driver: azure_file
